import { 
  Campaign, 
  ClipSubmission, 
  UserProfile, 
  CampaignParticipant, 
  SocialPlatform 
} from './types';
import { calculateClipPayout, parseSocialUrl } from './campaignUtils';

const BASE_TIME = 1740000000000;

export const GUEST_USER: UserProfile = {
  id: '',
  email: '',
  name: '',
  handle: '',
  role: 'creator',
  avatar: '🎬',
  bio: '',
  isLoggedIn: false,
  isProfileSetup: false,
  wallet_balance: 0,
  total_earned: 0,
  total_views_generated: 0,
  joinedCampaignIds: [],
};

export const INITIAL_CREATOR: UserProfile = GUEST_USER;

export const INITIAL_BRAND: UserProfile = {
  id: 'brand-cursor',
  name: 'Cursor AI',
  handle: '@cursor_dev',
  role: 'brand',
  avatar: '⚡',
  wallet_balance: 14500.00,
};

export const INITIAL_MARKETPLACE_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-cursor-01',
    brand_id: 'brand-cursor',
    brand_name: 'Cursor AI',
    brand_logo: '⚡',
    brand_url: 'https://cursor.com',
    brand_leaderboard_rank: 1,
    title: 'Cursor Composer & 10x Developer Speedruns',
    description: 'Create engaging short-form clips on X, Reels, or Shorts showcasing crazy coding speedruns, refactoring legacy code in 5 seconds, or building full apps using Cursor AI agent.',
    asset_drive_link: 'https://drive.google.com/drive/folders/1CursorRawFootageDemos2025',
    guidelines: {
      allowed_hashtags: ['#CursorAI', '#CodingSpeedrun', '#DevTok', '#BuildInPublic', '#AITools'],
      accounts_to_mention: ['@cursor_ai'],
      forbidden_audio: ['Copyrighted corporate music', 'Muffled speech without subtitles'],
      requirements: [
        'Must feature screen recording of Cursor AI Composer in action',
        'Add large bold captions/subtitles for key prompts',
        'Must include link in bio or tag @cursor_ai',
        'Min video duration: 25 seconds',
      ],
      notes: 'Focus on the "Wait, it wrote the entire backend?!" reaction moment.',
    },
    total_budget: 10000,
    remaining_budget: 6840,
    cpm_rate: 1.50, // $1.50 per 1k views
    max_payout_per_clip: 350,
    min_views_threshold: 2500,
    platforms: ['x', 'instagram', 'youtube_shorts'],
    category: 'DevTools',
    status: 'active',
    created_at: BASE_TIME - 1000 * 60 * 60 * 24 * 10,
    participants_count: 64,
    total_views_tracked: 2106000,
    total_paid_out: 3160,
  },
  {
    id: 'camp-lovable-02',
    brand_id: 'brand-lovable',
    brand_name: 'Lovable Dev',
    brand_logo: '❤️',
    brand_url: 'https://lovable.dev',
    brand_leaderboard_rank: 2,
    title: 'Prompt-to-SaaS in 60 Seconds Viral Clips',
    description: 'Post vertical hooks showing people building complete Tinder clones, CRM dashboards, or games using Lovable prompt engineer in under a minute.',
    asset_drive_link: 'https://drive.google.com/drive/folders/1LovableB-RollAndHookTemplates',
    guidelines: {
      allowed_hashtags: ['#LovableDev', '#NoCode', '#SaaS', '#IndieHacker', '#TechTok'],
      accounts_to_mention: ['@lovable_dev'],
      forbidden_audio: ['Explicit lyrics in first 5 seconds'],
      requirements: [
        'Split screen or facecam showing prompt typed -> app rendering live',
        'Show the actual usable deployed web app URL',
        'Hook within 2 seconds: "I made this app while drinking coffee"',
      ],
      notes: 'Highlight speed and zero coding barrier.',
    },
    total_budget: 8000,
    remaining_budget: 3450,
    cpm_rate: 1.25,
    max_payout_per_clip: 250,
    min_views_threshold: 3000,
    platforms: ['x', 'instagram', 'youtube_shorts'],
    category: 'AI & ML',
    status: 'active',
    created_at: BASE_TIME - 1000 * 60 * 60 * 24 * 7,
    participants_count: 48,
    total_views_tracked: 3640000,
    total_paid_out: 4550,
  },
  {
    id: 'camp-screenstudio-03',
    brand_id: 'brand-screenstudio',
    brand_name: 'Screen Studio',
    brand_logo: '🎥',
    brand_url: 'https://screen.studio',
    brand_leaderboard_rank: 12,
    title: 'Cinematic Screen Recording Transformations',
    description: 'Show side-by-side comparisons of default ugly screen recordings vs Screen Studio automatic zoom, cursor motion blur, and smooth shadows.',
    asset_drive_link: 'https://drive.google.com/drive/folders/1ScreenStudioRawClipsPackage',
    guidelines: {
      allowed_hashtags: ['#ScreenStudio', '#MacApps', '#DesignTok', '#VideoEditing', '#StartupDemo'],
      accounts_to_mention: ['@screenstudio_app'],
      forbidden_audio: ['Low bitrate voiceovers'],
      requirements: [
        'Before vs After visual comparison',
        'Show the cursor auto-zoom feature in action',
        'Mention "No keyframing required"',
      ],
      notes: 'Aesthetic visuals convert highest on X and Instagram Reels.',
    },
    total_budget: 5000,
    remaining_budget: 1820,
    cpm_rate: 1.80, // High CPM
    max_payout_per_clip: 400,
    min_views_threshold: 2000,
    platforms: ['instagram', 'x', 'youtube_shorts'],
    category: 'Design',
    status: 'active',
    created_at: BASE_TIME - 1000 * 60 * 60 * 24 * 5,
    participants_count: 32,
    total_views_tracked: 1766000,
    total_paid_out: 3180,
  },
  {
    id: 'camp-supabase-04',
    brand_id: 'brand-supabase',
    brand_name: 'Supabase Cloud',
    brand_logo: '⚡',
    brand_url: 'https://supabase.com',
    brand_leaderboard_rank: 7,
    title: '"Firebase is dead" - Postgres & AI Edge Functions Explainer',
    description: 'High energy technical clips comparing Firebase vendor lock-in vs open source Supabase Postgres with Vector search for AI agents.',
    asset_drive_link: 'https://drive.google.com/drive/folders/1SupabaseBrandKitsAndAnimations',
    guidelines: {
      allowed_hashtags: ['#Supabase', '#Postgres', '#WebDev', '#SoftwareEngineer', '#Database'],
      accounts_to_mention: ['@supabase'],
      forbidden_audio: ['None'],
      requirements: [
        'Must explain 1 technical benefit (Postgres SQL, realtime subscriptions, or vector)',
        'Include Supabase green brand mascot or sticker',
      ],
      notes: 'Developer humor and memes perform extremely well.',
    },
    total_budget: 6000,
    remaining_budget: 4900,
    cpm_rate: 1.40,
    max_payout_per_clip: 300,
    min_views_threshold: 4000,
    platforms: ['youtube_shorts', 'x'],
    category: 'DevTools',
    status: 'active',
    created_at: BASE_TIME - 1000 * 60 * 60 * 24 * 3,
    participants_count: 22,
    total_views_tracked: 785000,
    total_paid_out: 1100,
  },
  {
    id: 'camp-v0-05',
    brand_id: 'brand-v0',
    brand_name: 'v0 by Vercel',
    brand_logo: '▲',
    brand_url: 'https://v0.dev',
    brand_leaderboard_rank: 3,
    title: 'Generative UI Design Challenges',
    description: 'Clipper challenge: Give v0 the hardest, most complex design prompt (e.g. "Clone the Bloomberg Terminal in React") and react to the output.',
    asset_drive_link: 'https://drive.google.com/drive/folders/1V0VercelBrandAssetsAndSamples',
    guidelines: {
      allowed_hashtags: ['#v0', '#Vercel', '#Frontend', '#ReactJS', '#TailwindCSS'],
      accounts_to_mention: ['@v0', '@vercel'],
      forbidden_audio: ['Distorted sounds'],
      requirements: [
        'Show the prompt input and immediate React preview',
        'Show the code inspection tab with Tailwind / shadcn/ui',
      ],
      notes: 'Focus on developers and designers who want fast prototypes.',
    },
    total_budget: 7500,
    remaining_budget: 520, // Low budget left!
    cpm_rate: 1.10,
    max_payout_per_clip: 200,
    min_views_threshold: 2000,
    platforms: ['x', 'instagram', 'youtube_shorts'],
    category: 'DevTools',
    status: 'active',
    created_at: BASE_TIME - 1000 * 60 * 60 * 24 * 12,
    participants_count: 78,
    total_views_tracked: 6340000,
    total_paid_out: 6980,
  }
];

export const INITIAL_SUBMISSIONS: ClipSubmission[] = [
  {
    id: 'sub-01',
    campaign_id: 'camp-cursor-01',
    campaign_title: 'Cursor Composer & 10x Developer Speedruns',
    creator_id: 'creator-alex',
    creator_name: 'Alex Rivera (@alex_edits)',
    video_url: 'https://x.com/alex_edits/status/1733918204918237',
    platform: 'x',
    video_external_id: '1733918204918237',
    initial_view_count: 120,
    current_view_count: 148500,
    earned_amount: 222.75, // (148.5 - 0.12) * $1.50
    verification_status: 'active',
    submitted_at: BASE_TIME - 1000 * 60 * 60 * 48,
    last_polled_at: BASE_TIME - 1000 * 60 * 30,
    bot_velocity_score: 12,
  },
  {
    id: 'sub-02',
    campaign_id: 'camp-screenstudio-03',
    campaign_title: 'Cinematic Screen Recording Transformations',
    creator_id: 'creator-alex',
    creator_name: 'Alex Rivera (@alex_edits)',
    video_url: 'https://www.instagram.com/reel/C3x9z_ScreenStudioPro/',
    platform: 'instagram',
    video_external_id: 'C3x9z_ScreenStudioPro',
    initial_view_count: 450,
    current_view_count: 89400,
    earned_amount: 160.11, // (89.4 - 0.45) * $1.80
    verification_status: 'active',
    submitted_at: BASE_TIME - 1000 * 60 * 60 * 24,
    last_polled_at: BASE_TIME - 1000 * 60 * 15,
    bot_velocity_score: 8,
  },
  {
    id: 'sub-03',
    campaign_id: 'camp-cursor-01',
    campaign_title: 'Cursor Composer & 10x Developer Speedruns',
    creator_id: 'creator-alex',
    creator_name: 'Alex Rivera (@alex_edits)',
    video_url: 'https://www.youtube.com/shorts/dQw4w9CursorFast',
    platform: 'youtube_shorts',
    video_external_id: 'dQw4w9CursorFast',
    initial_view_count: 15,
    current_view_count: 1240, // Under 2500 threshold
    earned_amount: 0.00,
    verification_status: 'verifying',
    submitted_at: BASE_TIME - 1000 * 60 * 60 * 4,
    last_polled_at: BASE_TIME - 1000 * 60 * 5,
    bot_velocity_score: 4,
  }
];

export const INITIAL_PARTICIPANTS: CampaignParticipant[] = [
  {
    id: 'part-01',
    campaign_id: 'camp-cursor-01',
    creator_id: 'creator-demo-sample',
    joined_at: BASE_TIME - 1000 * 60 * 60 * 72,
    status: 'approved',
  },
  {
    id: 'part-02',
    campaign_id: 'camp-screenstudio-03',
    creator_id: 'creator-demo-sample',
    joined_at: BASE_TIME - 1000 * 60 * 60 * 36,
    status: 'approved',
  }
];
